name: Report an issue
description: Report a bug or issue with the project
title: "[BUG]"
type: bug
labels: [bug]
assignees: [ "IruNil6" ]

body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        This template is used for reporting an issues.

        Feature requests should be opened in [discussions]().

        Documentation request should also be opened in [discussions]().

        Before opening a new issue, please do a [search]() of existing issues to see if your issue has already been reported. If you find a similar issue, please add any additional information you have to that issue instead of opening a new one.
        ## Bug Report

        Please fill out the following sections to help us understand the issue you're experiencing.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: "Steps to reproduce the behavior."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "A clear and concise description of what you expected to happen."
  - type: dropdown
    attributes:
      label: Where is bug?
      description: Select where the bug is occurring.
      multiple: true
      options:
        - "Login Page"
        - "Main Panels Page"
        - "Panel Page"
    validations:
      required: true