name: Build NextTS Pull request

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu]
    
    name: Build NextTS Project for ${{ matrix.os }}

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Get version number from package
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: NPM install
        run: npm install
      - name: NPM build
        run: npm run build